<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Activity_logger_model extends CI_Model
{

    public $table = 'activity_logger';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('activity_logger.server_time', $this->order);
        $this->db->select("activity_logger.*, CASE WHEN activity_logger.activity LIKE 'Customer Portal login:%' THEN CONCAT('Customer Portal - ', TRIM(SUBSTRING_INDEX(SUBSTRING(activity_logger.activity, CHAR_LENGTH('Customer Portal login: ') + 1), ' [IP:', 1))) WHEN activity_logger.activity LIKE 'Customer Portal:%' THEN CONCAT('Customer Portal - ', TRIM(SUBSTRING_INDEX(SUBSTRING(activity_logger.activity, CHAR_LENGTH('Customer Portal: ') + 1), ' viewed ', 1))) WHEN activity_logger.user_id = 0 OR activity_logger.activity LIKE 'API:%' THEN 'Customer Portal / Public API' ELSE COALESCE(NULLIF(TRIM(CONCAT(employees.Firstname, ' ', employees.Lastname)), ''), CONCAT('System/User #', activity_logger.user_id)) END AS actor_name", FALSE)->from($this->table);
		$this->db->join('employees', 'employees.id=activity_logger.user_id', 'left');
        return $this->db->get()->result();
    }
function get_all_filter($status,$from,$to)
	{
$this->db->order_by('activity_logger.server_time', $this->order);
		$this->db->select("activity_logger.*, CASE WHEN activity_logger.activity LIKE 'Customer Portal login:%' THEN CONCAT('Customer Portal - ', TRIM(SUBSTRING_INDEX(SUBSTRING(activity_logger.activity, CHAR_LENGTH('Customer Portal login: ') + 1), ' [IP:', 1))) WHEN activity_logger.activity LIKE 'Customer Portal:%' THEN CONCAT('Customer Portal - ', TRIM(SUBSTRING_INDEX(SUBSTRING(activity_logger.activity, CHAR_LENGTH('Customer Portal: ') + 1), ' viewed ', 1))) WHEN activity_logger.user_id = 0 OR activity_logger.activity LIKE 'API:%' THEN 'Customer Portal / Public API' ELSE COALESCE(NULLIF(TRIM(CONCAT(employees.Firstname, ' ', employees.Lastname)), ''), CONCAT('System/User #', activity_logger.user_id)) END AS actor_name", FALSE)
		
			->from($this->table)
			->join('employees', 'employees.id=activity_logger.user_id', 'left');
        if ($status !== '' && $status !== null && $status !== 'All') {
            $this->db->where('activity_logger.activity_cate', $status);
        }
        if ($from !== '' && $from !== null) {
            $this->db->where('activity_logger.server_time >=', date('Y-m-d 00:00:00', strtotime($from)));
        }
        if ($to !== '' && $to !== null) {
            $this->db->where('activity_logger.server_time <=', date('Y-m-d 23:59:59', strtotime($to)));
        }
	
		return $this->db->get()->result();
	}
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('activity', $q);
	$this->db->or_like('system_time', $q);
	$this->db->or_like('server_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('activity', $q);
	$this->db->or_like('system_time', $q);
	$this->db->or_like('server_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Activity_logger_model.php */
/* Location: ./application/models/Activity_logger_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-14 06:27:32 */
/* http://harviacode.com */
