<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Branches_model extends CI_Model
{

    public $table = 'branches';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // Resolve legacy branch references stored as row ID, internal Code,
    // BranchCode, or BranchName.
    function get_by_reference($reference)
    {
        if ($reference === NULL || trim((string) $reference) === '') {
            return NULL;
        }

        $reference = trim((string) $reference);
        $this->db->group_start();
        if (ctype_digit($reference)) {
            $this->db->where('id', (int) $reference);
            $this->db->or_where('Code', $reference);
            $this->db->or_where('BranchCode', (int) $reference);
        } else {
            $this->db->where('LOWER(BranchName)', strtolower($reference));
            $this->db->or_where('LOWER(City)', strtolower($reference));
        }
        $this->db->group_end();

        return $this->db->get($this->table)->row();
    }

    function get_name_by_reference($reference)
    {
        $branch = $this->get_by_reference($reference);
        return $branch ? $branch->BranchName : ($reference ?: 'Not assigned');
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('BranchCode', $q);
	$this->db->or_like('BranchName', $q);
	$this->db->or_like('AddressLine1', $q);
	$this->db->or_like('AddressLine2', $q);
	$this->db->or_like('City', $q);
	$this->db->or_like('Stamp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('BranchCode', $q);
	$this->db->or_like('BranchName', $q);
	$this->db->or_like('AddressLine1', $q);
	$this->db->or_like('AddressLine2', $q);
	$this->db->or_like('City', $q);
	$this->db->or_like('Stamp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        return $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Branches_model.php */
/* Location: ./application/models/Branches_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-05 22:08:21 */
/* http://harviacode.com */
