<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Corporate_customers_model extends CI_Model
{

    public $table = 'corporate_customers';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
	function count_it() {

		$this->db->from($this->table);
		return $this->db->count_all_results();
	}
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
       
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	function update2($id, $data)
	{

		$this->db->where('ClientId', $id);
		$this->db->update($this->table, $data);
	}
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->group_start();
	$this->db->or_like('EntityName', $q);
	$this->db->or_like('DateOfIncorporation', $q);
	$this->db->or_like('RegistrationNumber', $q);
	$this->db->or_like('EntityType', $q);
	$this->db->or_like('ClientId', $q);
	$this->db->or_like('TaxIdentificationNumber', $q);
        $this->db->or_like('company_certificate', $q);
        $this->db->or_like('tax_id_doc', $q);
        $this->db->or_like('proof_physical_address', $q);
        $this->db->or_like('financial_statement', $q);
	$this->db->or_like('Country', $q);
	$this->db->or_like('Branch', $q);
	$this->db->or_like('Status', $q);
        $this->db->or_like('nature_of_business', $q);
        $this->db->or_like('industry_sector', $q);
        $this->db->or_like('street', $q);
        $this->db->or_like('city_town', $q);
        $this->db->or_like('province', $q);
        $this->db->or_like('postal_code', $q);
        $this->db->or_like('phone_number', $q);
        $this->db->or_like('contact_email', $q);
        $this->db->or_like('website', $q);
	$this->db->or_like('LastUpdatedOn', $q);
	$this->db->or_like('CreatedOn', $q);
		$this->db->group_end();
		$this->db->from($this->table)
			->where('approval_status','Approved');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->group_start();
	$this->db->or_like('EntityName', $q);
	$this->db->or_like('DateOfIncorporation', $q);
	$this->db->or_like('RegistrationNumber', $q);
	$this->db->or_like('EntityType', $q);
	$this->db->or_like('ClientId', $q);
	$this->db->or_like('TaxIdentificationNumber', $q);
        $this->db->or_like('company_certificate', $q);
        $this->db->or_like('tax_id_doc', $q);
        $this->db->or_like('proof_physical_address', $q);
        $this->db->or_like('financial_statement', $q);
	$this->db->or_like('Country', $q);
	$this->db->or_like('Branch', $q);
	$this->db->or_like('Status', $q);
        $this->db->or_like('nature_of_business', $q);
        $this->db->or_like('industry_sector', $q);
        $this->db->or_like('street', $q);
        $this->db->or_like('city_town', $q);
        $this->db->or_like('province', $q);
        $this->db->or_like('postal_code', $q);
        $this->db->or_like('phone_number', $q);
        $this->db->or_like('contact_email', $q);
        $this->db->or_like('website', $q);
	$this->db->or_like('LastUpdatedOn', $q);
	$this->db->or_like('CreatedOn', $q);
		$this->db->group_end();
		$this->db->from($this->table)
			->where('approval_status','Approved');
	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }
    function get_status($id)
    {

        $this->db->where('approval_status',$id);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Corporate_customers_model.php */
/* Location: ./application/models/Corporate_customers_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-05 22:08:22 */
/* http://harviacode.com */
