<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Currency_model extends CI_Model
{

    public $table = 'currency';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('symbol', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('is_local', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('symbol', $q);
	$this->db->or_like('code', $q);
	$this->db->or_like('is_local', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // Get all currencies from currencies table
    function get_all_currencies()
    {
        $this->db->order_by('currency_name', 'ASC');
        return $this->db->get('currencies')->result();
    }

    // Update exchange rate
    function update_exchange_rate($currency_id, $data)
    {
        $this->db->where('currency_id', $currency_id);
        return $this->db->update('currencies', $data);
    }

}

/* End of file Currency_model.php */
/* Location: ./application/models/Currency_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-14 06:27:32 */
/* http://harviacode.com */