<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Groups_model extends CI_Model
{

    public $table = 'groups';
    public $id = 'group_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select("*")->from($this->table)
			->join('employees','employees.id=groups.group_added_by')
			->join('branches','branches.id=groups.branch');
        return $this->db->get()->result();
    }
    function check($group_id)
    {

        $this->db->select("*")->from($this->table)
			->join('group_assigned_amount','group_assigned_amount.group_id=groups.group_id');
        	$this->db->where('group_assigned_amount.status','Active');
        	$this->db->where('groups.group_id',$group_id);
        	return $this->db->get()->row();
    }
    function get_all_active()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select("*")->from($this->table)
			->join('employees','employees.id=groups.group_added_by')
			->join('branches','branches.id=groups.branch');
        $this->db->where('group_status','Active');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
		$this->db->select("*")->from($this->table)
			->join('employees','employees.id=groups.group_added_by')
			->join('branches','branches.id=groups.branch');
        $this->db->where($this->id, $id);
        return $this->db->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('group_id', $q);
	$this->db->or_like('group_code', $q);
	$this->db->or_like('group_name', $q);
	$this->db->or_like('group_category', $q);
	$this->db->or_like('branch', $q);
	$this->db->or_like('group_description', $q);
	$this->db->or_like('group_added_by', $q);
	$this->db->or_like('group_registered_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('group_id', $q);
	$this->db->or_like('group_code', $q);
	$this->db->or_like('group_name', $q);
	$this->db->or_like('group_category', $q);
	$this->db->or_like('branch', $q);
	$this->db->or_like('group_description', $q);
	$this->db->or_like('group_added_by', $q);
	$this->db->or_like('group_registered_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
    
     function updateother($id,$other, $data)
    {
        $this->db->where('id', $id);
        $this->db->update($other, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Groups_model.php */
/* Location: ./application/models/Groups_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-18 06:00:15 */
/* http://harviacode.com */
