<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Loan_recommendation_model extends CI_Model
{

    public $table = 'loan_recommendation';
    public $id = 'loan_recomendation_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_by_loan($id)
    {
        $this->db->where('loan_id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('loan_recomendation_id', $q);
	$this->db->or_like('loan_id', $q);
	$this->db->or_like('application_form', $q);
	$this->db->or_like('application_form_comment', $q);
	$this->db->or_like('letter_from_auth', $q);
	$this->db->or_like('letter_from_auth_comment', $q);
	$this->db->or_like('commitment_fee', $q);
	$this->db->or_like('commitment_fee_comment', $q);
	$this->db->or_like('land_evidence', $q);
	$this->db->or_like('land_evidence_comment', $q);
	$this->db->or_like('offtaker_evidence', $q);
	$this->db->or_like('offtaker_evidence_comment', $q);
	$this->db->or_like('training_recieved', $q);
	$this->db->or_like('training_recieved_comment', $q);
	$this->db->or_like('loans_owed', $q);
	$this->db->or_like('loans_owed_comment', $q);
	$this->db->or_like('community_character', $q);
	$this->db->or_like('community_character_comment', $q);
	$this->db->or_like('date_stamp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('loan_recomendation_id', $q);
	$this->db->or_like('loan_id', $q);
	$this->db->or_like('application_form', $q);
	$this->db->or_like('application_form_comment', $q);
	$this->db->or_like('letter_from_auth', $q);
	$this->db->or_like('letter_from_auth_comment', $q);
	$this->db->or_like('commitment_fee', $q);
	$this->db->or_like('commitment_fee_comment', $q);
	$this->db->or_like('land_evidence', $q);
	$this->db->or_like('land_evidence_comment', $q);
	$this->db->or_like('offtaker_evidence', $q);
	$this->db->or_like('offtaker_evidence_comment', $q);
	$this->db->or_like('training_recieved', $q);
	$this->db->or_like('training_recieved_comment', $q);
	$this->db->or_like('loans_owed', $q);
	$this->db->or_like('loans_owed_comment', $q);
	$this->db->or_like('community_character', $q);
	$this->db->or_like('community_character_comment', $q);
	$this->db->or_like('date_stamp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Loan_recommendation_model.php */
/* Location: ./application/models/Loan_recommendation_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-16 13:13:13 */
/* http://harviacode.com */