<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Loan_files_model extends CI_Model
{

    public $table = 'loan_files';
    public $id = 'file_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_by_loans($id)
    {
        $this->db->where('loan_id', $id);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('file_id', $q);
	$this->db->or_like('loan_id', $q);
	$this->db->or_like('file_name', $q);
	$this->db->or_like('real_file', $q);
	$this->db->or_like('file_stamp', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('file_id', $q);
	$this->db->or_like('loan_id', $q);
	$this->db->or_like('file_name', $q);
	$this->db->or_like('real_file', $q);
	$this->db->or_like('file_stamp', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }


    function track_collateral($id)
    {
        $this->db->where('collateral_loan_id', $id);

        return $this->db->get('loan_collaterals')->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
    function insert_collateral($data)
    {
        $this->db->insert('loan_collaterals', $data);
    }
    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Loan_files_model.php */
/* Location: ./application/models/Loan_files_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-02-07 03:23:20 */
/* http://harviacode.com */