<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaction_model extends CI_Model
{

    public $table = 'transaction';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    function track_transactions($id)
    {
        $this->db->where('transaction.account_number', $id);
    
        return $this->db->get($this->table)->result();
    }

    function recomended_delete_transactions()
    {
        $this->db->where('is_recommended', 'yes');
        $this->db->where('delete_payment_status', 'no');

        return $this->db->get('delete_payments')->result();
    }
    // get all
    function approved_delete_transactions()
    {
        $this->db->where('is_recommended', 'yes');
        $this->db->where('delete_payment_status', 'no');
        return $this->db->get('delete_payments')->result();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
	public function get_my_transaction($account){
		$cdate = date('Y-m-d');
		$sql = "SELECT A.transaction_id AS transaction_id, A.system_time, A.account_number AS teller_account,A.credit,A.debit,A.balance,B.account_number As customer_account FROM transaction A , transaction B WHERE A.account_number <> B.account_number AND A.transaction_id = B.transaction_id AND A.account_number = '{$account}' AND DATE (A.server_time)='{$cdate}' ORDER BY A.id DESC ";
		return	$this->db->query($sql)->result();
//		return $this->db->get()->result();
	}
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('account_number', $q);
	$this->db->or_like('transaction_id', $q);
	$this->db->or_like('credit', $q);
	$this->db->or_like('debit', $q);
	$this->db->or_like('balance', $q);
	$this->db->or_like('system_time', $q);
	$this->db->or_like('server_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('account_number', $q);
	$this->db->or_like('transaction_id', $q);
	$this->db->or_like('credit', $q);
	$this->db->or_like('debit', $q);
	$this->db->or_like('balance', $q);
	$this->db->or_like('system_time', $q);
	$this->db->or_like('server_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaction_model.php */
/* Location: ./application/models/Transaction_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-31 21:06:36 */
/* http://harviacode.com */
